### ISSUE TITLE
Adapt to OPL3DUO (serial control OPL3 actual hardware)

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/libADLMIDI#256] opened 2022-10-25 11:07 UTC
https://github.com/DhrBaksteen/ArduinoOPL2/blob/master/examples/OPL3Duo/SerialPassthrough/SerialPassthrough.ino
https://github.com/DhrBaksteen/ArduinoOPL2/blob/master/examples/OPL2AudioBoard/SerialPassthrough/SerialPassthrough.ino

Currently I use SerialPassthrough.ino of OPL3DUO, compile these codes with arduino and upload them to arduino nano.
After that I use dosbox-x and specify the port number (like com3) and I can use the actual opl3 hardware.

**Comment by denjhang** [comment] 2022-10-25 11:08
By the way, OPL3BankEditor actually already supports this feature.

**Comment by Wohlstand** [comment] 2022-10-25 13:00
I will need to make use of extra chip interfaces, and make a different workflow way:
- for the case of emulated playback, I rely on sound output processing
- for the case of playing on real hardware, I will need to implement real-time processing (without using a built-in file player), OR, I'll just keep the real-time interface being used as a direct map to actual hardware, and you will need an external MIDI player program to use it.

**Comment by Wohlstand** [comment] 2023-11-25 02:41
Seems a duplicate of #246.

**Closed by Wohlstand** 2023-11-25 02:41 UTC
Labels: enhancement
